
services:
  # Servicio para la base de datos (usando PostgreSQL como ejemplo)
  db:
    image: postgres:13 # Usa la imagen oficial de PostgreSQL
    container_name: postgres_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # Puerto de la base de datos
    networks:
      - app_network

  # Servicio para tu aplicación Node.js
  app:
    build:
      context: . # Usa el Dockerfile en el directorio actual
    container_name: node_app_container
    environment:
      NODE_ENV: production
      DB_HOST: db # Nombre del servicio de la base de datos
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: database_name
    ports:
      - "3000:3000" # Puerto donde tu app estará disponible
    depends_on:
      - db
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data: